#!/usr/bin/env bash

# A script i stole from bread and modified to work for my needs.
# Uses nsxiv to show a wallpaper picker, a choice can be selected with "m" and quit with "q"
# This script then calls another script I stole from bread and modified
#
# This script is called with CMD+W in my keybinds

FOLDER=~/wallpaper # wallpaper folder
SCRIPT=~/.config/scripts/pywal16 # script to run after wal for refreshing programs, etc.

#display menu, save choice
menu () {
	CHOICE=$(nsxiv -otb $FOLDER/*)

#use waypaper to set wallpaper and call updating script based on choice
case $CHOICE in
		*.*) waypaper --wallpaper "$CHOICE";
		 wal -i "$CHOICE" -o $SCRIPT ;;
		*) exit 0 ;;
esac
}

#call menu
case "$#" in
    0) menu ;;
    *) exit 0 ;;
esac
